# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc52963136267cd5fe61f89991c3bd100e02ec1df871131d228ae5f4a382cb9e433b25fb2aef84f5526a720e1d16383d991d036da06e2f4e4badaef913a303d0

test:
  secret_key_base: dbbc899306581e9ee9fe971b5f2eb9002d2a8493bb53404556f507b7c383bf8ab3f10a97b9d1fa63d4b1f90b75c415b690b76fd90451cef6a45d2d78e3bc993f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
